[AddTaskConfig]
# 任务名称（必填，唯一，不可重复）
name = ""  
# 备份源目录（必填，单个路径，支持Windows和Linux路径）
backup_dir = ""  
# 备份存储目录（必填，单个路径，备份文件最终存放位置）
storage_dir = ""  


# 保留备份文件的数量（可选，默认3个；设置为0表示不按数量限制）
retain_count = 3
# 保留备份文件的天数（可选，默认7天；设置为0表示不按天数限制）
retain_days = 7


# 压缩策略（可选，默认"fast"；支持"fast"、"full"两种模式）
compress_strategy = "fast"


# 文件过滤规则（数组类型，支持多规则配置；规则语法：支持通配符*（匹配任意字符）、?（匹配单个字符），示例："*.log"匹配所有日志文件）
# 包含规则（可选，仅备份符合规则的文件；空数组表示备份所有文件）
include_rules = []
# 排除规则（可选，不备份符合规则的文件；优先级高于包含规则，即"先包含后排除"）
exclude_rules = []


# 最大文件大小（可选，超过此尺寸的文件不备份；示例：1073741824 = 1GB）
max_file_size = 0
# 最小文件大小（可选，小于此尺寸的文件不备份；示例：1024 = 1KB）
min_file_size = 0